### ISSUE TITLE
TumorComparer on Gene Subsets

### ISSUE THREAD

**Issue by cannin** [sanderlab/tumorcomparer#11]
We need a function that can take the entire dataset 

https://zenodo.org/record/4627644/files/tc_data_pancancer_march2021.tar.gz?download=1

and then can run TumorComparer on a subset of the genes using the generalized function. Here the weights will be 0 if not in the gene list and 1 otherwise. 

I imagine the code will take in a cancer type and a gene list. The rest (gene weights and using the 3 data types) will be handle by the code. 

It would be best to use the data as provided, but if you need to do transformations, let's discuss here what's necessary. 

This will go in the Shiny app where the above large data file will be available.

**Comment by cannin** [comment]
@Optimistix How was the pathway-specific analysis done in the paper? Figure 4 https://www.cell.com/cell-reports-methods/fulltext/S2667-2375(21)00084-9
Were all pathway genes present? If not, did you use the intersection across datatypes of available pathway genes? Or did you use all available genes within a data type? Or something else?

**Comment by Optimistix** [comment]
While I used all available genes within a data type, a case could be made for using the intersection across datatypes of available pathway genes.

**Comment by Optimistix** [comment]
Weights of 1 and 0 are equivalent to inclusion/exclusion, which can also be done by simply dropping the relevant genes/features, rather than carrying them all the way through, with zero weights.

The included/retained features, on the other hand, need not all have the same weight (e.g. 1) - in the manuscript, it was so because the pathway example was part of the "motivational" part, to show that the suitability of a model can vary by gene set. In the app/package, we can use different weights, e.g. if we choose all kinases, they may be given different weights using a similar approach to how a tool like OncoKB assigns tiers to mutations (say highest weight to genes bearing mutations with matched therapies in the given cancer, next to ones with matched therapies in some other cancer, and so on). We should also clarify with Chris whether he had something like this in mind.

**Comment by hakobyansiras** [comment]
I also used all available genes within the data types. 
@Optimistix did you unified all data types by samples? 
There are also differences in the number of samples between data types. Should I unify them?

**Comment by Optimistix** [comment]
@hakobyansiras - not sure what you mean by "did you unified all data types by samples?". I scaled each data type's similarity matrix to 0-1 using min-max scaling, to make the similarity values for the different data types comparable before taking their average. Did you mean something along those lines?

Also, what do you mean by "There are also differences in the number of samples between data types. Should I unify them?" - I assumed you were only using samples with all three data types available, otherwise how would you have all the required similarity values for the balloon plots? Are you using any samples which one or two data types?

**Comment by hakobyansiras** [comment]
There are 9124 mutual samples in all TCGA data types and 958 samples in CCLP. Mutual genes between TCGA and CCLP data types are:
Mutation: 14829
CNA: 16264
Expression: 14429

I would like to clarify if my and your numbers are matching, because I am not getting the same results as shown in the paper plot.
What "known_cancer_gene_weights_file" and "cancer_specific_gene_weights_file" you used? 
I have used the data from this link: https://zenodo.org/record/4627644#.YPH0mDszZH4

**Comment by Optimistix** [comment]
@hakobyansiras - refer to my earlier response & the paper; this is a comparison with uniform weights for all genes included. If you've been using the cancer-specific weights for SKCM & LIHC, then of course numbers won't match. An easy way to do this using the  "known_cancer_gene_weights_file" and "cancer_specific_gene_weights_file" approach (which is not mandatory) is to specify weights for all genes in the "known_cancer_gene_weights_file" (you need to create this: just set the weights to 1 for all pathway members, & 0 for all other genes). Weights from the "known_cancer_gene_weights_file" are only used for genes missing in the "cancer_specific_gene_weights_file", so in this case they'll be ignored. 

I hope that was clear, & that our numbers will match once you run it in the manner described above.

**Comment by cannin** [comment]
An initial function for geneset comparison has been added
