### ISSUE TITLE
Integrate Gene Set Analysis into Shiny App

### ISSUE THREAD

**Issue by cannin** [sanderlab/tumorcomparer#14]
1. The gene sets should be the 10 you are using now from the tcga_pancan_pathway_genes.rda 
2. Pre-computed results for these 10 genesets could appear under the pre-computed tab using a dropdown. The dropdown will either say "Most Variable Genes" or "X Pathway" (most variable genes default); @Optimistix needs to confirm "Most Variable Genes" label
3. The analysis should be also on the user analysis. Here is an example of an app that I tried to provide alternate run modes: 

https://cannin.shinyapps.io/targetscore/ (code: https://github.com/korkutlab/targetscore/tree/master/targetscore)

Perhaps we can two here as well. The main tumorcomparer mode (already there) and an alternative mode where only a gene set list is provided (text file one gene per line).

**Comment by Optimistix** [comment]
We can keep "Most Variable Genes" as the backup option, but try to come up with something better if possible - because that really only applies to the gene expression gene set, which is the genes with the highest variance across the TCGA pan-cancer dataset. For mutations, it's a consensus set of SMGs (from the TCGA pan-cancer paper on mutations), while for CNAs, it's all the genes contained in GISTIC peaks. So for mut & cna, "recurrently altered" is more accurate, but that has no equivalent for exp data. I think Chris doesn't like "dysregulated" - any other ideas/suggestions for a term that could apply to all three data types? If we can't come up with something better, we can always use "Most Variable Genes" along with an explanation.

**Comment by hakobyansiras** [comment]
Putting several screenshots of updated shiny app.
![image](https://user-images.githubusercontent.com/50982874/128422576-dee3fd91-7932-4ab7-af64-c6e4ea6f7fad.png)
![image](https://user-images.githubusercontent.com/50982874/128422646-e191d3cc-4262-49b6-9cbb-4f708c315cb5.png)
![image](https://user-images.githubusercontent.com/50982874/128422700-6b6954e3-ffcc-4ab0-bf7d-e2dedd6cfe12.png)

**Comment by Optimistix** [comment]
Siras - the x-axis is labelled "Weighted Similarity Ranks By Data Type", but the scores indicate that this is unlikely - e.g., the mut_scores of mostly 0s and a few 0.01s in the LGG Cell Cycle example. Can you  make sure that the label is "ranks" only when actual ranks are being displayed, and "scores" when scores are being displayed? Thanks!

**Comment by hakobyansiras** [comment]
What is the difference between the ranks and scores? How I can calculate(get) the ranks?

**Comment by cannin** [comment]
@hakobyansiras There is a parameter to change the label for the plot. That's all that needs to happen; you do not need to calculate the ranks. For the table, I cannot tell what tab. If you added the results on the pre-computed tab then there needs to be an if statement that can understand if a geneset was chosen and the column labels need to say score.

**Comment by cannin** [comment]
Initial analysis has been added
